coverage:
  status:
    project:
      default:
        target: 80%
  ignore:
    - "lastsaas/cmd/**"
    - "lastsaas/internal/db/**"
    - "lastsaas/internal/testutil/**"
    - "lastsaas/internal/configstore/**"
    - "lastsaas/internal/email/**"
    - "lastsaas/internal/health/**"
    - "lastsaas/internal/metrics/**"
    - "lastsaas/internal/planstore/**"
    - "lastsaas/internal/api/handlers/**"
